import type {Move, MoveFunctions, MoveId} from "../moves";

export const moveFunctionPatches: Partial<MoveFunctions> = {};

export const movePatches: Partial<Record<MoveId, Partial<Move>>> = {
  bind: {acc: 85},
  bonerush: {acc: 90},
  bulletseed: {power: 25},
  clamp: {acc: 85, pp: 15},
  cottonspore: {acc: 100},
  covet: {power: 60},
  crabhammer: {acc: 90},
  curse: {type: "ghost"},
  detect: {priority: +4},
  disable: {acc: 100},
  doomdesire: {power: 140, acc: 100},
  drainpunch: {power: 75, pp: 10},
  endure: {priority: +4},
  extremespeed: {priority: +2},
  fakeout: {priority: +3},
  feint: {power: 30},
  firespin: {power: 35, acc: 85},
  furycutter: {power: 20},
  futuresight: {power: 100, acc: 100, pp: 10},
  glare: {acc: 90},
  gigadrain: {power: 75},
  hijumpkick: {power: 130, pp: 10},
  iciclespear: {power: 25},
  jumpkick: {power: 100, pp: 10},
  lastresort: {power: 140},
  magmastorm: {acc: 75},
  outrage: {pp: 10},
  petaldance: {power: 120, pp: 10},
  poisongas: {acc: 90},
  protect: {priority: +4},
  rockblast: {acc: 90},
  sandtomb: {power: 35, acc: 85},
  tackle: {power: 50, acc: 100},
  thrash: {power: 120, pp: 10},
  toxic: {acc: 90},
  uproar: {power: 90},
  whirlpool: {power: 35, acc: 85},
  wrap: {acc: 90},
};
